
site_name: Jira Projekt
site_url: https://wczupryna.github.io/jira-projekt-dev/
use_directory_urls: false

nav:
  - Wstęp: index.md
  - Autorzy: autorzy.md
  - Konfiguracja: konfiguracja.md
  - Przykłady: przyklady.md
  - Tematy: tematy.md
  - Teoria: teoria.md
 
theme:
  name: mkdocs 

extra:
  base_url: /jira-projekt-dev/
extra_css:
  - stylesheets/custom.css